version: 2
jobs:
  build:
    working_directory: ~/aerogear
    docker:
      # Node 8 LTS
      - image: circleci/node:lts-browsers
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-dependencies
          command: npm install
      - run:
          name: install-package-dependencies
          command: npm run bootstrap
      - run:
          name: run-build
          command: npm run build
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          # Hoisting will cache some of the packages, but rest needs to be installed separtely
          name: install-package-dependencies-after-cache
          command: npm run bootstrap
      - run:
          name: run lint
          command: npm run lint
      - run:
          name: test
          command: npm test
      - run:
          name: coverage
          command: npm run coverage
      - run:
          name: sync integration test
          command: cd packages/sync && npm run integration-test
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results.xml
  npm_publish:
    working_directory: ~/aerogear
    docker:
      # Node 8 LTS
      - image: circleci/node:lts
    steps:
      - checkout
        # Allows us to authenticate with the npm registry
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run: CI=true npm run release:prep
      - run: TAG=$CIRCLE_TAG npm run release:validate
      - run: TAG=$CIRCLE_TAG npm run publish
  integration_test:
    working_directory: ~/aerogear
    docker:
      - image: circleci/node:lts
      - image: verdaccio/verdaccio
        name: verdaccio_instance
    steps:
      - checkout
        # publish npm packages to local verdaccio instance for testing
      - run: npm set registry http://verdaccio_instance:4873/
      - run: npx npm-cli-login -u test -p test -e test@example.com -r http://verdaccio_instance:4873
      - run: git config --global user.email "test@example.com"
      - run: git config --global user.name "test"
      - run: npx lerna version prerelease --no-push --yes
      - run: CI=true npm run release:prep
      - run: TAG=$CIRCLE_TAG npm run release:validate
      - run: TAG=$CIRCLE_TAG npm run publish
      - run: echo stop && false

workflows:
  version: 2
  build_and_release:
    jobs:
      - build:
          requires:
            - integration_test
          filters:
            tags:
              only: /.*/
      - integration_test:
          # requires:
          #   - build
          filters:
            tags:
              only: /.*/
      - npm_publish:
          requires:
            - integration_test
          filters:
            tags:
              only: /.*/ # allow anything because tag syntax is validated as part of validate-release.sh
            branches:
              ignore: /.*/
